{
 "title": "my a1 mbp",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU buys",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (sum(increase(node_cpu_seconds_total{mode=\"idle\",instance=\"localhost\"}[1m])) / sum(increase(node_cpu_seconds_total{instance=\"localhost\"}[1m]))) * 100",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Memery Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes) / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - sum(node_filesystem_free_bytes) / sum(node_filesystem_size_bytes)) * 100"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[1m]))",
     "legendFormat": "transmit"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total[1m]))",
     "legendFormat": "receive"
    }
   ]
  },
  {
   "title": "promhttp_metric_handler_requests_total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (job)(increase(promhttp_metric_handler_requests_total{code!=\"200\"}[1m]))"
    }
   ]
  }
 ]
}